# Generated by Django 6.0.2 on 2026-03-03 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('algorithm_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clusters',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category_reported', models.CharField(max_length=100)),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=5)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Closed', 'Closed'), ('In Progress', 'In Progress')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('impact', models.TextField()),
                ('root_cause', models.TextField()),
                ('resolution_steps', models.TextField()),
                ('service_component', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=50)),
                ('technology_stack', models.CharField(max_length=255)),
                ('runbook_available', models.BooleanField(db_index=True, default=False)),
                ('runbook_used', models.BooleanField(default=False)),
                ('manual_intervention', models.BooleanField(default=False)),
                ('true_category', models.CharField(db_index=True, max_length=50)),
                ('predicted_category', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('resolution_time_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runbooks', to='tickets.cluster')),
            ],
            options={
                'db_table': 'runbooks',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Postmortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('severity_snapshot', models.CharField(max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postmortems', to='tickets.ticket')),
            ],
            options={
                'db_table': 'postmortems',
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField()),
                ('model_used', models.CharField(max_length=100)),
                ('vector_dimension', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='tickets.ticket')),
            ],
            options={
                'db_table': 'embeddings',
            },
        ),
        migrations.CreateModel(
            name='TicketCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_clusters', to='tickets.cluster')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_clusters', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_clusters',
                'unique_together': {('ticket', 'cluster')},
            },
        ),
    ]
